FROM registry.access.redhat.com/ubi8/ubi

USER root

LABEL maintainer="John Doe"
LABEL version="1.0"
LABEL description="this is Containerfile"

# Labels consumed by RHOCP
LABEL io.k8s.description="A basic Apache HTTP Server S2I builder image" 
LABEL io.k8s.display-name="Apache HTTP Server S2I builder image for DO288" 
LABEL io.openshift.expose-services="80:http" 


# DocumentRoot for Apache
ENV DOCROOT=/var/www/html

RUN yum install -y --nodocs --disableplugin=subscription-manager httpd && \
 yum clean all --disableplugin=subscription-manager -y 
 
EXPOSE 80

# This stuff is needed to ensure a clean start

RUN mkdir -p /var/www/html 
RUN echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html
RUN rm -rf /run/httpd 
RUN  mkdir /run/httpd


# Launch httpd

CMD /usr/sbin/httpd -DFOREGROUND
